version: '3.8'

  # Total Service: 4 -----> (frontend, backend, mongo, nginx)
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://localhost:27017/dd_db
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist/angular-15-crud:/usr/share/nginx/html:ro
    depends_on:
      - frontend

volumes:
  mongo-data:
